const NEET_DATA = [
    { institute: "AIIMS Delhi", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 57 },
    { institute: "AIIMS Delhi", branch: "MBBS", category: "OBC-NCL", gender: "Gender-Neutral", closing_rank: 255 },
    { institute: "AIIMS Delhi", branch: "MBBS", category: "SC", gender: "Gender-Neutral", closing_rank: 989 },
    { institute: "JIPMER Puducherry", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 277 },
    { institute: "JIPMER Puducherry", branch: "MBBS", category: "OBC-NCL", gender: "Gender-Neutral", closing_rank: 580 },
    { institute: "Vardhman Mahavir Medical College (VMMC), Delhi", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 107 },
    { institute: "Maulana Azad Medical College (MAMC), Delhi", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 87 },
    { institute: "Maulana Azad Medical College (MAMC), Delhi", branch: "MBBS", category: "OBC-NCL", gender: "Gender-Neutral", closing_rank: 372 },
    { institute: "Madras Medical College, Chennai", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 747 },
    { institute: "Madras Medical College, Chennai", branch: "MBBS", category: "OBC-NCL", gender: "Gender-Neutral", closing_rank: 1247 },
    { institute: "Seth GS Medical College, Mumbai", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 656 },
    { institute: "AIIMS Bhubaneswar", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 491 },
    { institute: "AIIMS Jodhpur", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 497 },
    { institute: "AIIMS Bhopal", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 558 },
    { institute: "AIIMS Rishikesh", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 773 },
    { institute: "King George's Medical University (KGMU), Lucknow", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 1097 },
    { institute: "King George's Medical University (KGMU), Lucknow", branch: "MBBS", category: "OBC-NCL", gender: "Gender-Neutral", closing_rank: 1697 },
    { institute: "King George's Medical University (KGMU), Lucknow", branch: "MBBS", category: "SC", gender: "Gender-Neutral", closing_rank: 21097 },
    { institute: "Institute of Medical Sciences, BHU, Varanasi", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 858 },
    { institute: "Grant Medical College, Mumbai", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 1618 },
    { institute: "Bangalore Medical College", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 1200 },
    { institute: "BJ Medical College, Ahmedabad", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 714 },
    { institute: "Government Medical College, Chandigarh", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 500 },
    { institute: "Government Medical College, Nagpur", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 3500 },
    { institute: "Government Medical College, Surat", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 4100 },
    { institute: "Indira Gandhi Medical College, Shimla", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 2800 },
    { institute: "Patna Medical College", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 3000 },
    { institute: "SMS Medical College, Jaipur", branch: "MBBS", category: "OPEN", gender: "Gender-Neutral", closing_rank: 1150 },
    { institute: "SMS Medical College, Jaipur", branch: "MBBS", category: "OBC-NCL", gender: "Gender-Neutral", closing_rank: 1850 },
    { institute: "Lady Hardinge Medical College, Delhi", branch: "MBBS", category: "OPEN", gender: "Female-Only", closing_rank: 485 },
    { institute: "Lady Hardinge Medical College, Delhi", branch: "MBBS", category: "OBC-NCL", gender: "Female-Only", closing_rank: 985 }
];
